### ISSUE TITLE
How to provide organization name

### ISSUE THREAD

**Issue by zen** [mineiros-io/terraform-github-organization#42]
Hi guys,

This module looks very interesting, although I have one problem. I'm managing multiple organizations on GH, how can I actually tell the module which one I want to manage? Am I missing something here?

**Comment by zen** [comment]
OK, looks like this is set at the provider level. Working like a charm

**Comment by soerenmartius** [comment]
Hi @zen,

Thanks for reaching out! Exactly you can either set the organization through the `owner` variable or by using the `GITHUB_OWNER` environment variable. For details please see https://registry.terraform.io/providers/integrations/github/latest/docs#owner

Merry Christmas!

**Comment by soerenmartius** [comment]
I will add this to the docs also!
