### ISSUE TITLE
join the organization

### ISSUE THREAD

**Issue by samuelbarrionuevo** [mineiros-io/terraform-github-organization#47]
1. I would like to contribute to the repository as a collaborator, greetings
2. https://www.terraform.io/language/values/variables

**Comment by soerenmartius** [comment]
Hey @samuelbarrionuevo, thanks for reaching out and showing interest in contributing to this repository. For instructions on how to contribute to this repository please https://github.com/mineiros-io/terraform-github-organization/blob/main/CONTRIBUTING.md

Basically, you would need to fork the repository and add changes back to this repo by opening pull requests. Thank You!
